services:
    dc:
        build: .
        command: ["python","main.py","--log","debug"]
        privileged: true
        volumes:
            - ./config:/app/config
        environment:
            - DCSM_CONFIG=/app/config/old_config.toml
        networks:
            internal:
                aliases:
                    - dc.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-dc
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
