services:
    dc:
        extends:
            file: dc/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - dc.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-dc
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
