#=-= Define Interface Modules =-=
[interface.spi0]
    module="testing"
    class="Dummy"
[interface.spi0.config]
    bus=0
    device=0
    speed=1000000
    mode=0

#=-= Define Device Modules =-=
#[device.adc_0]
#    module="adc_MCP300X"
#    class="MCP3008"
#    interface="spi0"
#[device.adc_0.config]
#    adc_channel="1"
#[device.adc_0.variables]
#    v_in = "v_amp_out"

[device.adc_0]
    module="testing"
    class="MockDeviceRandom"
    interface="spi0"
[device.adc_0.config]
    max=1.0
[device.adc_0.variables]
    variable = "v_amp_out"

[device.adc_1]
    module="testing"
    class="MockDeviceRandom"
    interface="spi0"
[device.adc_1.config]
    max=2.0
[device.adc_1.variables]
    variable = "v_amp_out"

[device.adc_2]
    module="testing"
    class="MockDeviceRandom"
    interface="spi0"
[device.adc_2.config]
    max=1.5
[device.adc_2.variables]
    variable = "v_amp_out"

#=-= Define Calculation Modules =-=
[calculation.power]
    module="gen_electrical"
    class="PowerToCurrent"
[calculation.power.config]
    line_voltage = 230
    phases = 1
[calculation.power.variables]
    power_in = "power"
    rms_current_out = "current_rms"

[calculation.rms_current]
    module="gen_electrical"
    class="RMSToPeak"
[calculation.rms_current.variables]
    var_in = "current_rms"
    var_out = "clamp_current"

[calculation.current_clamp]
    module="gen_current_clamp"
    class="VoltageClamp"
[calculation.current_clamp.config]
    nominal_current = 20
[calculation.current_clamp.variables]
    current_in = "clamp_current"
    voltage_out = "v_amp_in"

[calculation.amplifier]
    module="gen_amplifier"
    class="GenAmplifier"
[calculation.amplifier.config]
    gain = 2
[calculation.amplifier.variables]
    amp_input = "v_amp_in"
    amp_output = "v_amp_out"

#=-= Define Calculation Pipelines =-=
[pipelines]
    single_clamp = ["power","rms_current","current_clamp","amplifier"]

#=-= Define Measurements Pipelines =-=
#[measurement]
#    module="gen_sample"
#    class="SingleSampleAvg"
#[measurement.config]
#    period = 1.0 # seconds
#    n_samples = 5
#[[measurement.sensing_stacks]]
#    device = "adc_0"
#    pipeline = "single_clamp"

[measurement]
    module="gen_sample"
    class="MultiSampleMergedAvg"
[measurement.config]
    period = 1.0 # seconds
    n_samples = 5
[[measurement.sensing_stacks]]
    prefix = "a_"
    device = "adc_0"
    pipeline = "single_clamp"
    constants = {'phase'='A'}
[[measurement.sensing_stacks]]
    prefix = "b_"
    device = "adc_1"
    pipeline = "single_clamp"
    constants = {'phase'='B'}
[[measurement.sensing_stacks]]
    prefix = "c_"
    device = "adc_2"
    pipeline = "single_clamp"
    constants = {'phase'='C'}

[output]
    path = "power_monitoring/{{machine}}"
#[output.spec]
#    timestamp = '$.timestamp'
#    power = '$.power'
#    current = "$.current_rms"
#    phase = "$.phase"
#    machine="#Machine_1"

[[output.spec]]
    timestamp = '$.timestamp'
    power = '$.a_power'
    current = "$.a_current_rms"
    phase = "$.a_phase"
    machine="#Machine_1"
[[output.spec]]
    timestamp = '$.timestamp'
    power = '$.b_power'
    current = "$.b_current_rms"
    phase = "$.b_phase"
    machine="#Machine_1"
[[output.spec]]
    timestamp = '$.timestamp'
    power = '$.c_power'
    current = "$.c_current_rms"
    phase = "$.c_phase"
    machine="#Machine_1"


[mqtt]
    broker = "192.168.56.110"
    port = 1883   #common mqtt ports are 1883 and 8883
    base_topic_template = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds